name: Scaffold New Repository
description: 'Scaffolds a new repository with Terraform configuration to create the repository'

inputs:
  repository:
    description: 'Name for the new repository (name only)'
    required: true
    type: string
  token:
    description: 'GitHub Token with repo and workflow permissions'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Create terraform.tfvars with inputs
      run: |
        cat <<'EOF' > ${{ github.action_path }}/terraform.tfvars
        token = "${{ inputs.token }}"
        github_repository = "${{ inputs.repository }}"
        EOF
        cat ${{ github.action_path }}/terraform.tfvars
      shell: bash
    - name: Apply Terraform to Scaffold Repository
      uses: ./.github/actions/terraform-apply
      with:
        working-directory: ${{ github.action_path }}

    # - name: Apply Terraform to Scaffold Repository
    #   uses: ./.github/actions/terraform-apply
    #   with:
    #     working-directory: ./.github/actions/scaffold-repository/terraform
    #     variables-json: |
    #       {
    #         "repository_name": "${{ inputs.repository }}",
    #         "github_token": "${{ inputs.token }}"
    #       }

