name: Scaffold Deployment Environment
description: 'Scaffolds a new repository with Terraform configuration to create the repository'

inputs:
  repository:
    description: 'Name for the new repository (name only)'
    required: true
    type: string
  token:
    description: 'GitHub Token with repo and workflow permissions'
    required: true
    type: string
  variables:
    description: Content for Terraform variable files
    required: false
    default: ''
    type: string

runs:
  using: 'composite'
  steps:
    - name: Create terraform.tfvars with inputs
      shell: bash
      run: |
        cat <<'EOF' > ${{ github.action_path }}/terraform.tfvars
        ${{inputs.variables}}
        EOF

    - name: Apply Terraform to Scaffold Repository
      uses: ./.github/actions/terraform-apply
      with:
        working-directory: ${{ github.action_path }}
